# Libraries needed

In [4]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

# Environment

In [17]:
env = gym.make('FrozenLake-v1')

# Environment variables

In [9]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
exploration_decay_rate = 0.01
max_exploration_rate = 1
min_exploration_rate = 0.01

# Creating Q table

In [10]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n


q_table = np.zeros((state_space_size,action_space_size))

#  Values in Q table

In [11]:
print(q_table)
print('Shape of Q table:',q_table.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of Q table: (16, 4)


# Used to observe the rewards of each episode later

In [12]:
rewards_all_episodes = []

Q- Learning Algo

# Q-learning

In [13]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    reward_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_threshold_rate = random.uniform(0,1)
        if exploration_threshold_rate > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        #  Taking action
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        # Setting new state
        state = new_state
        
        # Reward added
        reward_current_episode += reward
        
        if done == True:
            break
        
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    # Adding rewards
    rewards_all_episodes.append(reward_current_episode)

ValueError: too many values to unpack (expected 4)

In [15]:
sum(rewards_all_episodes)

0

# Calculate and print the average reward per thousand episodes

In [60]:
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(sum(r))
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

148.0
1000 :  0.1480000000000001
374.0
2000 :  0.3740000000000003
461.0
3000 :  0.46100000000000035
611.0
4000 :  0.6110000000000004
685.0
5000 :  0.6850000000000005
661.0
6000 :  0.6610000000000005
686.0
7000 :  0.6860000000000005
672.0
8000 :  0.6720000000000005
673.0
9000 :  0.6730000000000005
692.0
10000 :  0.6920000000000005


In [ ]:
#printing Q-table

In [41]:
print('*******************Printing Q-table*********************')
print(q_table)

*******************Printing Q-table*********************
[[0.49078225 0.48306048 0.48041237 0.48111699]
 [0.04597387 0.11992721 0.08159627 0.41024931]
 [0.34445548 0.11192129 0.18892832 0.18017268]
 [0.16366031 0.0114866  0.01605195 0.00592224]
 [0.50873226 0.37036186 0.38418876 0.34374653]
 [0.         0.         0.         0.        ]
 [0.25677036 0.09052331 0.19151453 0.07884768]
 [0.         0.         0.         0.        ]
 [0.28965285 0.34925899 0.51417273 0.52971535]
 [0.49508282 0.54471131 0.36145508 0.30401291]
 [0.38946241 0.39023528 0.36064053 0.19682267]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.43833609 0.62038084 0.66553858 0.48457965]
 [0.7222739  0.75733151 0.69874904 0.72719256]
 [0.         0.         0.         0.        ]]


# Watch the agent play

In [3]:
all_episode_actions = []
for episode in range(3):
    state = env.reset()
    done = False
    print('********Starting episode ', episode, ' ********')
    time.sleep(1)
    
    current_episode_actions = []  # Initialize list to store actions for the current episode
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
       
        action = np.argmax(q_table[state,:])
        current_episode_actions.append(action)  # Append action to current episode actions
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            if reward == 1:
                print('Agent reached the goal and won the episode.', episode)
                time.sleep(1)
            else:
                print('Agent stepped in a hole and lost episode.', episode)
                time.sleep(1)
            clear_output(wait=True)
            break
        state = new_state
    
    all_episode_actions.append(current_episode_actions)  # Append list of actions for current episode to all episodes

env.close()       

NameError: name 'env' is not defined

In [62]:
env.reset()
env.step(1)

(1, 0.0, False, {'prob': 0.3333333333333333})

In [65]:
print(all_episode_actions)


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 3, 3, 0, 3, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 3, 0, 0, 3, 0, 3, 1, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 3, 1, 2, 1], [0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 1, 3, 0, 0, 0, 3, 1, 3, 1, 0, 0, 0, 1]]
